POST (http://localhost:3000/register/)
Content-Type: application/json

{
    "username":"Akhil",
    "name":"Akhil Lakkimsetti",
    "password":"akhil123",
    "gender":"Male",
    "location":"Kodamanchili"
}

###
POST (http://localhost:3000/login/)
Content-Type: application/json

{
    
  "username": "Akhil",
  "password": "akhil123"

}